#!/bin/bash
mysql -u root -p"$MYSQL_ROOT_PASSWORD" <<-EOSQL
  CREATE USER IF NOT EXISTS '$MYSQL_REPL_USER'@'%' IDENTIFIED BY '$MYSQL_REPL_PASSWORD';
  GRANT REPLICATION SLAVE ON *.* TO '$MYSQL_REPL_USER'@'%';
  FLUSH PRIVILEGES;
EOSQL